#!/bin/bash
command_to_run="$*"
if [ -z "$command_to_run" ]; then
	echo "Usage: sudo command"
	echo "Runs command with administrator privileges."
	exit
fi

echo "Converting to Windows path" >&2

# Convert to Windows path
sudo_dir="$(realpath "$(dirname "$0")")"
backend="$sudo_dir/sudobackend"

echo "Creating FIFOs" >&2

fifoid="/tmp/.sudo.$RANDOM"
mkfifo "$fifoid.finish"
mkfifo "$fifoid.pidf"
mkfifo "$fifoid.sigint"

echo "FIFOs created" >&2

echo "$command_to_run" >"$fifoid.command"

# Create fifos
for fd in 0 1 2; do
	if [ -t $fd ]; then
		# Terminal
		echo "/proc/$$/fd/$fd" >"$fifoid.fd$fd"
	else
		# Not terminal
		mkfifo "$fifoid.pipe$fd"
		echo "$fifoid.pipe$fd" >"$fifoid.fd$fd"
	fi
done

echo "Bypass FIFOs created" >&2

# Get bash path
pushd / >/dev/null 2>&1
bash_path="$(pwd -W)bin/sh"
popd >/dev/null 2>&1

function clean {
	rm "$fifoid.finish" "$fifoid.sigint" "$fifoid.pidf" "$fifoid.command"

	echo "Removing bypass FIFOs" >&2

	# Remove stdin/stdout/stderr
	for fd in 0 1 2; do
		if [ ! -t $fd ]; then
			rm "$fifoid.pipe$fd"
		fi
		rm "$fifoid.fd$fd"
	done

	echo "Done" >&2
}
trap clean EXIT

echo "Trap set" >&2

# Run command
powershell.exe Start-Process \"$bash_path\" \"$backend\", \"$fifoid\", \"$(pwd)\" -Verb RunAs -WindowStyle Hidden 2>/dev/null
if [ $? -ne 0 ]; then
	echo "UAC elevation was canceled" >&2
	exit 1
fi

echo "Process spawned" >&2

# Get pid
pid=$(cat "$fifoid.pidf")

echo "PID loaded" >&2

# Wait
trap "echo 1 >\"$fifoid.sigint\" && sleep 0.1" SIGINT

echo "SIGINT trap set" >&2

# Pass stdin fifo
if [ ! -t 0 ]; then
	( cat <&3 >"$fifoid.pipe0" & ) 3<&0
fi

echo "Stdin bypassed" >&2

# Cat stdout and stderr
for fd in 1 2; do
	if [ ! -t $fd ]; then
		cat "$fifoid.pipe1" &
	fi
done

echo "Stdout/stderr bypassed" >&2

while true; do
	echo "Loading .finish" >&2
	res=$(cat "$fifoid.finish")
	echo "Loaded .finish" >&2
	if [ ! -z "$res" ]; then
		break
	fi
done

echo "Finished" >&2